name: deepposture-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.1
  - scikit-learn=1.5.2
  - numpy
  - pandas
  - scipy
  - h5py
  - tqdm
